### PR TITLE
[WIP] Add support for multiple arguments

### LINKED ISSUE #1: Only first parameter is logged
The `console.log()`-API supports multiple parameters. Example in Firefox Dev-Tools:

2016-09-19 01_13_49-new tab

See also https://developer.mozilla.org/en-US/docs/Web/API/Console/log.

### PR DESCRIPTION
**Pull request by ulrichb**
Fixes #1.

### TODO
- [ ] Discuss a slight behavior change I've added. Previously, if `logToConsole`-option was false, we suppressed logging (completely) when `onlyConsole=true`. I've changed that, so that now `console.skipHtml` does _not_ suppress logging even when `logToConsole`-option is `false`. Is this OK? If not, the `logToConsole`-check simply has to be moved into the `console.skipHtml[method]` function.
- [ ] Finish README update.
- [ ] Run dist script & commit results.
- [ ] Update version.

If I run `npm run dist` on master (without changes) with the latest npm packages, I get a lot of changes in the jsdoc files. Same on your machine?

How can I trigger a [CI run for the PR](https://travis-ci.org/Alorel/console-log-html/pull_requests)?

### CODE REVIEW

**Comment by Alorel** [comment]
@ulrichb Looks good so far. Travis not triggering on a pull request was my own mess-up as I accidentally had those turned off. They should trigger on the next pull. I'll merge this with develop now and post a link to the Travis run

**Comment by Alorel** [comment]
The build is available at [https://travis-ci.org/Alorel/console-log-html/builds/161271930](https://travis-ci.org/Alorel/console-log-html/builds/161271930). On a side note, would you know why the PhantomJS browser might not be getting stored in cache as expected? Bitbucket (where PhantomJS is downloaded from) has some rate limiting set up, so multiple builds in a short period of time may cause some builds to error.

**Comment by Alorel** [comment]
Some other notes:

- The suppression changes are fine, as long as they're reflected in the README.
- skipHtml as described in the readme changes [doesn't seem to work](https://jsfiddle.net/fsn4rwra/1/) (open your console then run)

**Comment by ulrichb** [comment]
Hi Alorel,
* Fixed README
* Ad "skipHtml"-sample: Hmm, I do see the log entry in the console. I've also created a second demo with jsbin: https://jsbin.com/hudogo/edit?html,console,output
* I have a lot more changes in the jsdoc-output (see commit https://github.com/Alorel/console-log-html/pull/3/commits/bbfa649b2f90f03620d44e008a74b3a80aa192af). You don't? (Have you tried to delete `node_modules` and reinstall everything?

=> I've created the follow-up PR #3 for the README changes & the dict-script output.

**Comment by Alorel** [comment]
Yep, it's just an updated version of the jsdoc theme. I'll give it a quick test-run myself and, if you're satisfied, merge it into master.

**Pull request merged**
