### PR TITLE
"Append at bottom" option

### PR DESCRIPTION
**Pull request by ulrichb**
Allows to configure the same output-order as Firefox, Chrome, node.js-output.

2016-09-23 14_11_40-js bin - collaborative javascript debugging - jsbin com

Name "appendAtBottom" (default=false) to be discussed. Is the negation "appendAtTop" (default=true) better?

### CODE REVIEW

**Comment by Alorel** [comment]
As you know what you're doing, do you want me to just add you as a collaborator to this project? It would save you having to make pull requests

**Comment by ulrichb** [comment]
Thanks. Yeah, adding me to the contributors would be great. I've no more changes planned, but when I will have something, I will still create a PR to be able to use the review tooling of GitHub. For the case that you have any  comments/suggestions.

And thanks for merging.

**Comment by Alorel** [comment]
Thanks for contributing! Your invite is now [pending](https://github.com/Alorel/console-log-html/invitations).

**Comment by ulrichb** [comment]
Thx.

**Pull request merged**
